### ISSUE TITLE
Future of this library

### ISSUE THREAD

**Issue by hartman** [nyurik/mw-graph-shared#5]
So... now that graphoid is dead, and there is no direct successor to it coming any time soon, I'm wondering if it makes sense to keep this as a separate library atm. I'm considering just merging the code into the graph extension to break free of this dependency for now, just to facilitate easier maintenance and make it easier to at least get client side to a newer version of Vega.

Would probably still go into a separate directory of the main repo, just in case we ever get a render server again, but I don't have very high hopes. 

what do you think @nyurik ?

**Comment by nyurik** [comment]
@hartman yes, that would make perfect sense
